### ISSUE TITLE
Rename `wp checksum core` back to `wp core verify-checksums`

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/checksum-command#14]
The original rename is a decision I regret. Most WP-CLI commands are verbs, so we should make this a verb too.

**Comment by schlessera** [comment]
How about `wp verify`?

- `wp verify core`
- `wp verify plugin --all`
- `wp verify theme --all`
- `wp verify all`

**Comment by danielbachhuber** [comment]
`wp verify` is too ambiguous.

**Comment by schlessera** [comment]
And the same stack with `verify-checksums` instead?

**Comment by schlessera** [comment]
I just don't think that this should be split amongst multiple commands. There's a lot of code reuse, and the most used scenario will probably be `verify all the stuff`, once we have implemented that.

**Comment by danielbachhuber** [comment]
> I just don't think that this should be split amongst multiple commands. There's a lot of code reuse,

We can use PHP inheritance to DRY our code without forcing our naming structure to a specific pattern.

> And the same stack with `verify-checksums` instead?

Most commands are `wp <noun> <verb>`. I think we should follow this existing pattern for consistency.

**Comment by schlessera** [comment]
Before I go about renaming the commands again, I'd like to make sure we're on the same page.

We now have core checksums and plugin checksums (and themes will be aded later as well).

Right now, these are implemented in `wp-cli/checksum-command` and are named:
* `wp checksum core`
* `wp checksum plugin` (in separate branch right now)

What we want is:
* `wp core verify-checksums` (with alias `wp checksum core`)
* `wp plugin verify-checksums` (with alias `wp checksum plugin`)

These will stay in the `wp-cli/checksum-command` repository (instead of splitting them out into the `wp-cli/core-command` and `wp-cli/extension-command` repositories.

@danielbachhuber Do you agree with all of the above?

**Comment by danielbachhuber** [comment]
👍 from me if it seems fine to you

**Comment by schlessera** [comment]
I'll put my OCD neatly into a drawer away from the laptop, to ignore the repository name mismatch... ;)
