### ISSUE TITLE
Provide hardcoded edge case for `hello` plugin installed by Core

### ISSUE THREAD

**Issue by schlessera** [wp-cli/checksum-command#33]
A standard WordPress install contains a single file version of the Hello Dolly plugin called `hello.php`.

The related plugin in the plugin repository is named `hello-dolly` and is a subfolder with multiple files.

We need to provide a hardcoded edge case detection for this plugin.

**Comment by shawnhooper** [comment]
I'm working on this issue.  

I have an updated checksum-command working with the hardcoded edge case, but am running into the problem.

### Problem

The `hello.php` file in core and the `hello.php` file in the `hello-dolly` repo plugin slightly different, so the checksums fail. 

The only difference is a text-domain added on line 62 in the plugin version that doesn't exist in core:

![image](https://github.com/wp-cli/checksum-command/assets/2073284/4135a5c8-bc63-4f36-bbd3-6c138cb220c5)

### Possible Solutions

1. Update WordPress Core to include the hello-dolly textdomain 

2. Update the Hello Dolly plugin to remove the textdomain, assuming that it's been translated in all supported versions of Core. 

3. Validate `hello.php` against the core version of `hello.php` (I don't like this solution since we could run into version conflicts between the plugin and the installed version of core)

**Comment by swissspidy** [comment]
Oooh, I see!

Yes I think you're right, the `hello.php` translations are part of the core translations, so the absent text domain makes sense. And the `hello-dolly` plugin has the text domain has a translation because that's expected for plugins, so that makes sense too.

I think option (3) makes most sense because the core checksums API _does_ contain the checksum for `hello.php`

**Comment by shawnhooper** [comment]
@swissspidy So the only possible problem I see there is that `hello.php` in the plugins folder could have come from an older version of Core, and be different.  Verifying checksum against the version in the installed version of Core would then fail.

**Comment by swissspidy** [comment]
Ah, that‘s a good point! We would need to check whether that file is updated when upgrading WordPress. If it is, then it might be an unlikely edge case. Thoughts?

The thing with (1) and (2) is that this won‘t be possible/accepted.

**Comment by shawnhooper** [comment]
From @wojsmol in Slack: 

```
hello.php placed directly  in wp-content/plugins is updated thogrther with core and for that reason it's checksum in returned from core checksum api. Plugin version of this plugin is paced in wp-content/plugins/hello-dolly/ folder.
```

Based on this, I'm going to update the PR to compare `hello.php` against the installed version of WordPress.
