### ISSUE TITLE
Flag presence of unexpected files

### ISSUE THREAD

**Issue by paulschreiber** [wp-cli/checksum-command#74]
## Feature Request
- [X] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).

**Describe your use case and the problem you are facing**

Someone installed malware on my server. It came in two parts:
• modifying `wp-includes/general-template.php`
• adding `temp/modules.php`

`wp core verify-checksums` caught the first case but not the second.

**Describe the solution you'd like**

Any unexpected files (outside wp-content) should result in an error.

**Comment by jasongill** [comment]
Doesn't this really fall outside of the scope of wp-cli - is it up to the WordPress command line tools to monitor for the presence of non-WordPress files? Additionally, wouldn't this cause tons of false positives as many (most?) sites have a variety of files not managed by WordPress, from things like robots.txt or Google site verification text files, to junk added by webhosts, to old files or versions of the site?

It sounds like wp-cli would do what it intended to in this case - identifying modified files that were part of WordPress - while not reporting files that WordPress has no clue about (how would wp-cli know that temp/modules.php was bad, and not something you needed for your site?).

**Comment by paulschreiber** [comment]
If you don't want to change the default behaviour, adding a `--check-extra-files` flag (or similar) could solve this problem.

**Comment by jasongill** [comment]
> If you don't want to change the default behaviour, adding a `--check-extra-files` flag (or similar) could solve this problem.

This isn't really a problem that wp-cli is intended to solve though, is it? wp core verify-checksums does what it says on the tin: verifies the checksums of the files provided by WordPress, as well as identifying files that are masquerading as WordPress files (by being inside of wp-includes or wp-admin directories where no outside files belong).

You could just run `find` on your webroot and exclude the wp-admin and wp-includes directories (in addition to `wp core verify-checksums` of course) to alert you of any new files that may need to be investigated.

**Comment by paulschreiber** [comment]
But then everyone would have to create/maintain their own list of core files, which isn't great.

**Comment by jasongill** [comment]
> But then everyone would have to create/maintain their own list of core files, which isn't great.

`wp core verify-checksums` already verifies core files. There is no need to make a list - it already does this.

What you are asking is for it to identify regular files which are not trying to hide themselves inside of WordPress, which is the focus of the verify-checksums feature. Since that can already be done with other simple tools and is beyond the scope of this project, there is really no reason to add anything to wp-cli, as it would be a duplication of effort to what's already built in to your OS, but it would also result in false positives for the majority who have non-WP files in their website directories. Since the tool wouldn't be able to identify if these non-WP files were malicious or not, there's absolutely no benefit to it compared to running `find`

**Comment by paulschreiber** [comment]
I disagree. It would be very helpful to be aware of the presence of any unexpected files.

**Comment by jasongill** [comment]
`find -not -path "./wp-admin/*" -not -path "./wp-includes/*" -not -name "wp-*.php"` already does exactly what you want and is provided with your OS - it will show you any files that aren't being scanned by `wp core verify-checksums`

What you are basically saying is "My house caught on fire, and during the fire my pipes burst. The smoke alarm warned me about the fire, but it didn't warn me about the water damage! Why can't we add a water sensor to the smoke alarm?"

You are trying to use the wrong tool for the job, and at best the modification you request would print tons of false negatives (for example, your requested modification would list everything in wp-content - are you going to go through and check all of those files?); or at worst, if directories like wp-content were excluded, it would give a sense of false security (attackers hide files in wp-content all the time).

There are many other tools to do exactly what you want even better, and the only reason that `wp core verify-checksums` is needed is because of it's ability to grab the official WordPress checksums and compare the files on disk. The variety of benign files that could exist which your suggested modification would "catch" is endless, and in reality has nothing to do with what wp-cli is meant to do.

**Comment by paulschreiber** [comment]
Hmm. I don't think we're on the same page here. I want to be alerted if `/wp-includes/wp-suspicious-file.php` (or `/wp-sktechy-file.php` or `/sketchy-file.php`) is found.

It's not reasonable of me to keep a whitelist of everything in /, /wp-admin/, /wp-includes/ and update that list with every release and run a diff. And each server admin/site owner would have to duplicate effort to write all that code.

My expectation is that `wp core verify-checksums` ensures (ignoring `wp-content`):
* all expected files are present
* all expected files unmodified
* no unexpected files are present

**Comment by jasongill** [comment]
As I've said, `wp core verify-checksums` already does this. It scans for files that shouldn't belong in wp-includes and wp-admin as well as files named wp-*.php

The issue is that you want the tool to also find files that aren't trying to hide themselves as WordPress files and list them. This is beyond the scope of the tool, as like you said - we would exclude wp-content of course, which would totally invalidate any security benefit of doing this, as a bad file hiding in wp-content is just as bad as one hiding in another subdirectory. 

The entire point of the verify-checksums feature is to find files that are modified or are trying to hide themselves as WordPress files, since the layperson isn't going to be able to quickly determine what files are supposed to be in wp-includes (for example). Since the tool can pull the checksum list and compare it, it tells the user what files are in places that they don't belong compared to a normal WP install. You're trying to find files that aren't trying to hide - and that is already easily accomplished with the find command or a myriad of other purpose built tools (just like wp-cli is purpose built to deal with WordPress, not made to deal with trying to identify files that could be malicious and are not related to WordPress).

**Comment by danielbachhuber** [comment]
@paulschreiber Will this be solved by https://github.com/wp-cli/checksum-command/pull/102 ?
