### ISSUE TITLE
Core verify-checksums command doesn't catch added files at ABSPATH directory

### ISSUE THREAD

**Issue by timoshka-lab** [wp-cli/checksum-command#81]
Thanks for a great project, It very helpful to me in many cases.
I have to report you one thing i found in `core verify-checksums` command behavior.

The `wp core verify-checksums` command warns about added files which should not be exists,
but it doesn't matches files was added to ABSPATH directory.

### Reproduction
Just add some file named like `sample.php` to wordpress installation directory,
and run `wp core verify-checksums` command. It won't show you any warnings about `sample.php` file was added.
But if you move `sample.php` into `wp-includes` directory, then warnings will works fine.

I think it depends on `filter_file` method at : [https://github.com/wp-cli/checksum-command/blob/master/src/Checksum_Core_Command.php#L130-L135](https://github.com/wp-cli/checksum-command/blob/master/src/Checksum_Core_Command.php#L130-L135)

Take a look please.
Thanks for your time.

**Comment by jasongill** [comment]
I believe that this is actually a feature, not a bug. `wp core verify-checksums` will verify the checksum of the WordPress-related files in the root directory, but does not check for the addition of new files in the root directory. This is because you could (and very likely do) have other non-WordPress related files in the root directory of your site, which cannot be verified.

So, having a robots.txt or an /images/ folder or some other unrelated PHP script in the root directory of the site is fine; we just want to be sure that none of the WordPress scripts in the root directory have been modified. But, having some files hidden in wp-includes is bad, as there should not be anything in that directory which isn't WordPress-related.

If we were to start alerting on unexpected files in the root directory, then it would just lead to tons of false positives which would not be ideal.

I think the tool, as it is now, does it's job of making sure that none of WordPress'es core files have been modified, and that nothing else is trying to be included in an area where most webmasters wouldn't look/wouldn't know if it was really created by WordPress or not.

**Comment by timoshka-lab** [comment]
Thanks for reply @jasongill.
I agree to your opinion. But at the same time, I think it would be nice to have two options like ‘—include-root’ and ‘—exclude’ to keep current usage safe for current users and provide functions to keep root to be safe too.

For the users who want to keep them root directory safly, they would able to use ‘ wp core verify-checksums —include-root —exclude=images’.

**Comment by paulschreiber** [comment]
I agree 100% with @timoshka-lab. I have come across multiple instance of malware dumping files in the root directory.
